### ISSUE TITLE
Nearest neighbour / spatial join with attribute condition

### ISSUE THREAD

**Issue by NabilMik** [mkoenigb/ProcessX#4]
Hello 

unfortunately the nearest neighbour join with attribute condition for example same name of the two line layers is not working.
I tried different layers.

Maybe you have an idea, why it is not working ?

Thank you in advance and best regards from basel

Nabil

**Comment by NabilMik** [comment]
Ive recognized that the Plugin is still not working correctly
I have uploaded an example dataset here
https://www.swisstransfer.com/d/d67ac6c3-614e-4752-a50f-e52f087c1826

**Comment by mkoenigb** [comment]
Solved by https://gis.stackexchange.com/q/464004/107424
