### ISSUE TITLE
Is this a bug in NearestPointsToPath?

### ISSUE THREAD

**Issue by Walshe-d** [mkoenigb/ProcessX#5]
I'm trying to use the ProcessX in QGIS 3.32.3. and I get the following error when using a point layer. I have all the optional parameters as default:

Traceback (most recent call last):
File "/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ProcessX/algorithms/vector_creation/NearestPointsToPath.py", line 117, in processAlgorithm
(sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context,
TypeError: QgsProcessingAlgorithm.parameterAsSink(): argument 5 has unexpected type 'int'

Line 117 is as follows:
(sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context,
output_layer_fields, 2, # LineString = 2
source_layer.sourceCrs())

**Comment by Walshe-d** [comment]
I looked at the code in main/algorithms/vector_creation/NearestPointsToPath.py and found that line 117 is actually 

   (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context,
                                               output_layer_fields, QgsWkbTypes.LineString, # LineString = 2
                                               source_layer.sourceCrs())

I've changed the 5th argument from 2 to QgsWkbTypes.LineString and the function works perfectly.

Not sure how the plugins work exactly/are setup but it seems like it is reading a different version of this script.

When running the Nearest points to path, it calls the script located at .local/share/QGIS/QGIS3/profiles/default/python/plugins/ProcessX/algorithms/vector_creation/NearestPointsToPath.py which is different to main/algorithms/vector_creation/NearestPointsToPath.py

Hopefully this is an easy fix.

**Comment by mkoenigb** [comment]
That is not a bug. That is due to a change in some QGIS version. I fixed it after it was reported here: https://github.com/mkoenigb/ProcessX/issues/3 but never made a release of it in QGIS Plugin repository because I thought I will fix some other things too before, but had no time for since then.
