### ISSUE TITLE
QGIS 3.36.0-Maidenhead on Ubuntu Linux some install warning and then QGIS startup errors

### ISSUE THREAD

**Issue by marcobra** [mkoenigb/ProcessX#6]
Hi on QGIS 3.36.0-Maidenhead on Ubuntu Linux, there are some warnings related to some parameters during install process and then on QGIS startup.
I'm at home now, tomorrow i will send here here more detailed report about this.

Please check difference of "type" param https://qgis.org/pyqgis/3.34/core/QgsProcessingParameterNumber.html 

Thanks

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/vector_conditionals/JoinAttributesByNearestWithCondition.py", line 68, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Versione Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 3 has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/vector_conditionals/SelectDuplicatesBySimilarity.py", line 42, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Versione Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

TypeError: QgsProcessingParameterField(): arguments did not match any overloaded call:   overload 1: argument 5 has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/vector_creation/GeometryLayerFromGeojsonStringField.py", line 35, in initAlgorithm
    QgsProcessingParameterField(
TypeError: QgsProcessingParameterField(): arguments did not match any overloaded call:
  overload 1: argument 5 has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'
  
  
  TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/vector_creation/CreateNestedGrid.py", line 76, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Versione Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/vector_creation/RandomlyRedistributeFeaturesInsidePolygon.py", line 52, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Versione Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/opentripplanner/OtpRoutes.py", line 125, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Versione Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/marco/python/plugins/ProcessX/algorithms/opentripplanner/OtpTraveltime.py", line 88, in initAlgorithm
    QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

**Comment by mkoenigb** [comment]
Thank you for reporting this.

Seems like the type arguments in QgsProcessingParameterNumber() and QgsProcessingParameterField() (probably even more QgsProcessingParameter's) have changed in QGIS 3.36 and type arguments can now no longer be a number but have to be for example QgsProcessingParameterNumber.Double respectively QgsProcessingParameterNumber.Integer for QgsProcessingParameterNumber() and QgsProcessingParameterField.String etc. for QgsProcessingParameterField(). 
So it should be an easy fix. I will try to provide an update soon. Meanwhile there is unfortunately no other option than using 3.34 or other older versions for affected algorithms.

**Comment by mkoenigb** [comment]
This is now fixed with version 1.7.1, available here on github and as soon as approved on plugins.qgis.org.

**Comment by marcobra** [comment]
Glad to help, thanks
