### ISSUE TITLE
QGIS Modeler Issue - Fails to create files properly

### ISSUE THREAD

**Issue by astuartmiller** [mkoenigb/ProcessX#8]
![image](https://github.com/mkoenigb/ProcessX/assets/127142701/5ac96370-32c9-4263-aff7-8b59cb9037dc)
![image](https://github.com/mkoenigb/ProcessX/assets/127142701/d93abeb4-c61c-4fbf-bd82-3afbf8e2869e)
![image](https://github.com/mkoenigb/ProcessX/assets/127142701/2187a7b3-f6a6-4c9f-a793-880f32558836)

When I run this as a temporary layer output it works fine. However, when I batch the process I get an error stating that the files were not created correctly. I am saving to a file path with no spaces, and have tried .shp and gpkg with the same results

**Comment by mkoenigb** [comment]
Not sure if this error is related to "count points in polygons with condition". At least the error you show does not indicate this.

Does it run fine if you replace "count points in polygons with condition" with the native "count points in polygon" algorithm?

**Comment by astuartmiller** [comment]
> Not sure if this error is related to "count points in polygons with condition". At least the error you show does not indicate this.
> 
> Does it run fine if you replace "count points in polygons with condition" with the native "count points in polygon" algorithm?

The native count points in polygon was not producing errors, but with multiple points overlapping the counts were inaccurate. The only other change was adding "create spatial index" to increase the processing speed.

Its strange that it will run as a temporary layer with no issue, and when I converted the script to python it also produced no errors. If batch processing the script works I'll be able to move forward, thats great but I would like to know whats causing the issue in case there are problems down the line.

**Comment by mkoenigb** [comment]
Ok I can reproduce the issue. It does not only affect this algorithm but potentially all algorithms including all native algorithms. I assume there may be some bug in the model builder. Tested with 3.36.0 and native algorithms intersection and point to path.

For now I cannot see a cause for this in one of the algorithms from this plug in. I suggest to open a bug report in the official QGIS repository here: https://github.com/qgis/QGIS/issues

Please also review https://gis.stackexchange.com/questions/467219/attributeerror-in-qgis-model-during-batchmode-processing and the suggested solution to check "load layers on completion". For my tests this resolves the error.

**Comment by astuartmiller** [comment]
I really appreciate the quick response! That post has definitely helped, and I will keep it in mind going forward. I was really scratching my head on this.
